export const NOTIFY_MESSAGE = 'NOTIFY_MESSAGE';
export const DISABLE_BALANCE_ON_EDIT = 'DISABLE_BALANCE_ON_EDIT'
export const DISABLE_EDIT = 'DISABLE_EDIT'
export const DISABLE_REGISTER = 'DISABLE_REGISTER'